begin;
select plan(20);
select has_table('public','organizations','organizations exists');
select has_table('public','business_units','business_units exists');
select has_table('public','branches','branches exists');
select has_table('public','customers','customers exists');
select has_table('public','inventory_units','inventory_units exists');
select has_table('public','inventory_transfers','inventory_transfers exists');
select has_table('public','audit_logs','audit_logs exists');
select has_function('public','dispatch_inventory_transfer',array['uuid','text[]'],'dispatch is transactional RPC');
select has_function('public','receive_inventory_transfer',array['uuid','text[]'],'receive is transactional RPC');
select col_is_unique('public','customers',array['organization_id','normalized_dni'],'DNI unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','imei_1'],'IMEI1 unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','imei_2'],'IMEI2 unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','serial_number'],'serial unique per organization');
select row_security_active('public','customers','customers RLS enabled');
select row_security_active('public','inventory_units','inventory RLS enabled');
select row_security_active('public','credit_applications','applications RLS enabled');
select row_security_active('public','transfer_reports','transfer reports RLS enabled');
select row_security_active('public','customer_documents','documents RLS enabled');
select policies_are('public','audit_logs',array['audit_read'],'audit only exposes read policy');
select triggers_are('public','audit_logs',array['audit_logs_immutable'],'audit is immutable');
select * from finish();
rollback;
