begin;
select plan(32);
select has_table('public','organizations','organizations exists');
select has_table('public','business_units','business_units exists');
select has_table('public','branches','branches exists');
select has_table('public','customers','customers exists');
select has_table('public','inventory_units','inventory_units exists');
select has_table('public','inventory_transfers','inventory_transfers exists');
select has_table('public','audit_logs','audit_logs exists');
select has_table('public','credit_accounts','credit accounts exists');
select has_table('public','credit_installments','installments exist');
select has_table('public','customer_portal_access','portal access exists');
select has_table('public','payment_applications','payment applications exist');
select has_table('public','collection_actions','collection actions exist');
select has_function('public','dispatch_inventory_transfer',array['uuid','text[]'],'dispatch is transactional RPC');
select has_function('public','receive_inventory_transfer',array['uuid','text[]'],'receive is transactional RPC');
select has_function('public','submit_credit_application',array['uuid','uuid','text','text','text','text','text','numeric','numeric','integer'],'credit submission is transactional');
select has_function('public','decide_credit_application',array['uuid','text','text','jsonb'],'credit decision is transactional');
select has_function('public','create_inventory_transfer',array['uuid','uuid','uuid[]'],'transfer creation is transactional');
select has_function('public','report_customer_payment',array['uuid','uuid','uuid','text','numeric','date','text','text'],'portal payment reporting exists');
select has_function('public','validate_customer_payment',array['uuid','boolean','text'],'payment validation exists');
select has_function('public','record_collection_action',array['uuid','text','text','date'],'collections workflow exists');
select col_is_unique('public','customers',array['organization_id','normalized_dni'],'DNI unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','imei_1'],'IMEI1 unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','imei_2'],'IMEI2 unique per organization');
select col_is_unique('public','inventory_units',array['organization_id','serial_number'],'serial unique per organization');
select row_security_active('public','customers','customers RLS enabled');
select row_security_active('public','inventory_units','inventory RLS enabled');
select row_security_active('public','credit_applications','applications RLS enabled');
select row_security_active('public','transfer_reports','transfer reports RLS enabled');
select row_security_active('public','customer_documents','documents RLS enabled');
select row_security_active('public','credit_accounts','credit accounts RLS enabled');
select policies_are('public','audit_logs',array['audit_read'],'audit only exposes read policy');
select triggers_are('public','audit_logs',array['audit_logs_immutable'],'audit is immutable');
select * from finish();
rollback;
