project_id = "credicel"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://credi-cel-admin-web.vercel.app"
additional_redirect_urls = ["https://credi-cel-admin-web.vercel.app/**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email.template.confirmation]
subject = "Confirma tu cuenta de CrediCel"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.invite]
subject = "Te invitaron a trabajar en CrediCel"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Recupera tu acceso a CrediCel"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Tu enlace seguro de acceso a CrediCel"
content_path = "./supabase/templates/magic-link.html"

[auth.email.template.email_change]
subject = "Confirma tu nuevo correo de CrediCel"
content_path = "./supabase/templates/email-change.html"

[auth.email.template.reauthentication]
subject = "Código de seguridad de CrediCel"
content_path = "./supabase/templates/reauthentication.html"

[storage]
enabled = true
file_size_limit = "50MiB"
