const fields:Readonly<Record<string,readonly {readonly name:string;readonly label:string;readonly type?:string}[]>>={
  organizacion:[{name:"commercial_name",label:"Nombre comercial"},{name:"legal_name",label:"Razón social"},{name:"owner_name",label:"Propietario o socio"},{name:"rtn",label:"RTN"},{name:"branch_name",label:"Nombre del punto"},{name:"branch_code",label:"Código del punto"}],
  usuarios:[{name:"full_name",label:"Nombre completo"},{name:"email",label:"Correo",type:"email"},{name:"role",label:"Rol"},{name:"branches",label:"Puntos autorizados"}],
  clientes:[{name:"first_name",label:"Nombres"},{name:"last_name",label:"Apellidos"},{name:"dni",label:"DNI"},{name:"phone",label:"Teléfono"},{name:"email",label:"Correo",type:"email"}],
  expedientes:[{name:"customer",label:"Cliente"},{name:"document_type",label:"Tipo de documento"},{name:"file",label:"Archivo privado",type:"file"},{name:"holder_relationship",label:"Relación del titular"}],
  inventario:[{name:"imei_1",label:"IMEI 1"},{name:"imei_2",label:"IMEI 2"},{name:"serial",label:"Número de serie"},{name:"model",label:"Marca y modelo"},{name:"owner",label:"Unidad propietaria"},{name:"branch",label:"Ubicación física"}],
  transferencias:[{name:"origin",label:"Punto de origen"},{name:"destination",label:"Punto de destino"},{name:"imei",label:"Escanear IMEI"},{name:"ownership",label:"Transferencia de propiedad"}],
  solicitudes:[{name:"customer",label:"Cliente"},{name:"inventory",label:"Equipo por IMEI"},{name:"requested_price",label:"Precio solicitado",type:"number"},{name:"down_payment",label:"Prima propuesta",type:"number"},{name:"term",label:"Plazo propuesto",type:"number"}],
  pagos:[{name:"origin_bank",label:"Banco de origen"},{name:"amount",label:"Monto",type:"number"},{name:"date",label:"Fecha",type:"date"},{name:"reference",label:"Referencia"},{name:"holder",label:"Titular emisor"},{name:"receipt",label:"Comprobante",type:"file"}],
  configuracion:[{name:"key",label:"Clave"},{name:"scope",label:"Ámbito"},{name:"value",label:"Valor"},{name:"priority",label:"Prioridad",type:"number"},{name:"effective_from",label:"Vigente desde",type:"date"},{name:"version",label:"Versión",type:"number"}],
};
export function SectionWorkspace({section}:{readonly section:string}){const sectionFields=fields[section];if(!sectionFields)return <div className="empty">Este módulo se habilitará cuando existan registros relacionados.</div>;return <div className="card"><form className="form">{sectionFields.map((field)=><div className="field" key={field.name}><label htmlFor={field.name}>{field.label}</label><input id={field.name} name={field.name} type={field.type??"text"}/></div>)}<div><button className="button" type="submit">Guardar borrador</button></div></form><p className="muted">El guardado definitivo requiere sesión Supabase, permisos RLS y las variables públicas configuradas.</p></div>}
