const fields: Readonly<Record<string, readonly { readonly name: string; readonly label: string; readonly type?: string }[]>> = {
  organizacion: [{ name: "commercial_name", label: "Nombre comercial" }, { name: "legal_name", label: "Razón social" }, { name: "rtn", label: "RTN" }, { name: "branch_name", label: "Nombre de la tienda" }, { name: "branch_code", label: "Código de la tienda" }],
  usuarios: [{ name: "full_name", label: "Nombre completo" }, { name: "email", label: "Correo", type: "email" }, { name: "role", label: "Rol" }, { name: "branches", label: "Tiendas autorizadas" }],
  inventario: [{ name: "imei_1", label: "IMEI 1" }, { name: "imei_2", label: "IMEI 2" }, { name: "serial", label: "Número de serie" }, { name: "model", label: "Marca y modelo" }, { name: "branch", label: "Tienda" }],
  transferencias: [{ name: "origin", label: "Tienda de origen" }, { name: "destination", label: "Tienda de destino" }, { name: "imei", label: "Escanear IMEI" }],
  pagos: [{ name: "amount", label: "Monto", type: "number" }, { name: "date", label: "Fecha", type: "date" }, { name: "reference", label: "Referencia" }, { name: "receipt", label: "Comprobante", type: "file" }],
  configuracion: [{ name: "key", label: "Configuración" }, { name: "value", label: "Valor" }],
};

const statusLabels: Readonly<Record<string, string>> = { approved: "Aprobada", rejected: "Rechazada", activated: "Crédito activo", under_review: "En revisión", pending: "Pendiente", conditional: "Condicionada", conditioned: "Condicionada", delinquent: "En mora", overdue: "En mora", available: "Disponible", reserved: "Reservado", sold: "Vendido", active: "Activo", inactive: "Inactivo", in_transit: "En tránsito", received: "Recibido" };
const statusClass = (status: string) => ["rejected", "delinquent", "overdue"].includes(status) ? "danger" : ["under_review", "pending", "conditional", "conditioned", "in_transit"].includes(status) ? "warning" : "success";
export interface WorkspaceRecord { readonly id: string; readonly title: string; readonly detail: string; readonly status: string }

export function SectionWorkspace({ section, records }: { readonly section: string; readonly records: readonly WorkspaceRecord[] }) {
  const sectionFields = fields[section];
  return <div className="workspace-stack">{records.length > 0 && <div className="card records-card"><div className="form-title"><div><h2>Registros recientes</h2><p className="muted">{records.length} elementos encontrados</p></div></div><div className="record-list">{records.map((record) => <article className="record" key={record.id}><div><strong>{record.title}</strong><span>{record.detail}</span></div><span className={`badge ${statusClass(record.status)}`}>{statusLabels[record.status] ?? record.status}</span></article>)}</div></div>}{sectionFields ? <div className="card form-card"><div className="form-title"><div><h2>Nuevo registro</h2><p className="muted">Completa la información para continuar.</p></div><span className="step">Paso 1 de 1</span></div><form className="form">{sectionFields.map((field) => <div className="field" key={field.name}><label htmlFor={field.name}>{field.label}</label><input id={field.name} name={field.name} type={field.type ?? "text"} /></div>)}<div className="form-actions"><button className="button" type="submit">Guardar</button><button className="button secondary" type="reset">Limpiar</button></div></form></div> : records.length === 0 && <div className="empty"><div className="empty-icon">✓</div><strong>Todo en orden</strong><span>No hay elementos pendientes.</span></div>}</div>;
}
