"use server";
import { redirect } from "next/navigation";
import { createServerSupabase } from "@/lib/supabase/server";
const text=(f:FormData,n:string)=>String(f.get(n)??"");const number=(f:FormData,n:string)=>Number(f.get(n)??0);
export async function submitCreditApplication(formData:FormData){
 const supabase=await createServerSupabase();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
 const{data,error}=await supabase.rpc("submit_complete_credit_application",{p_branch_id:text(formData,"branch_id"),p_inventory_unit_id:text(formData,"inventory_unit_id"),p_dni:text(formData,"dni"),p_first_name:text(formData,"first_name"),p_last_name:text(formData,"last_name"),p_phone:text(formData,"phone"),p_email:text(formData,"email"),p_requested_price:number(formData,"requested_price"),p_down_payment:number(formData,"down_payment"),p_term:number(formData,"term"),p_birth_date:text(formData,"birth_date"),p_marital_status:text(formData,"marital_status"),p_dependents:number(formData,"dependents"),p_current_address:text(formData,"current_address"),p_housing_type:text(formData,"housing_type"),p_employer_name:text(formData,"employer_name"),p_job_title:text(formData,"job_title"),p_monthly_income:number(formData,"monthly_income"),p_monthly_expenses:number(formData,"monthly_expenses"),p_employment_months:number(formData,"employment_months"),p_reference_one_name:text(formData,"reference_one_name"),p_reference_one_phone:text(formData,"reference_one_phone"),p_reference_one_relationship:text(formData,"reference_one_relationship"),p_reference_two_name:text(formData,"reference_two_name"),p_reference_two_phone:text(formData,"reference_two_phone"),p_reference_two_relationship:text(formData,"reference_two_relationship"),p_consent_data_processing:formData.get("consent_data_processing")==="on",p_consent_credit_review:formData.get("consent_credit_review")==="on"});
 if(error)redirect(`/ventas?error=${encodeURIComponent(error.message)}`);
 const{data:application}=await supabase.from("credit_applications").select("customer_id,organization_id").eq("id",String(data)).single();
 if(application){for(const documentType of["dni_front","dni_back","selfie","address_proof"]as const){const file=formData.get(documentType);if(!(file instanceof File)||file.size===0)continue;const extension=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${application.organization_id}/${application.customer_id}/${crypto.randomUUID()}/${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await supabase.storage.from("customer-documents").upload(path,file,{contentType:file.type,upsert:false});if(!uploadError)await supabase.from("customer_documents").insert({organization_id:application.organization_id,customer_id:application.customer_id,document_type:documentType,storage_path:path});}}
 await supabase.rpc("refresh_credit_assessment",{p_application_id:String(data)});
 redirect(`/mis-ventas?created=${data}`);
}
