drop policy if exists customers_scoped_read on public.customers;
create policy customers_scoped_read on public.customers for select to authenticated using(organization_id=private.current_organization_id()and(private.has_role('organization_owner')or private.has_role('organization_admin')or private.has_role('credit_manager')or(private.has_role('collections_agent')and exists(select 1 from public.credit_accounts ca where ca.customer_id=customers.id))or exists(select 1 from public.customer_assignments ca where ca.customer_id=customers.id and ca.ended_at is null and(case when private.has_role('salesperson')then ca.salesperson_id=auth.uid() when private.has_role('branch_manager')then private.has_branch_access(ca.branch_id)else false end))or(private.has_role('credit_analyst')and exists(select 1 from public.credit_applications a where a.customer_id=customers.id and private.has_branch_access(a.branch_id)))));

create or replace function public.validate_customer_payment(p_report_id uuid,p_approve boolean,p_notes text)returns void language plpgsql security definer set search_path='' as $$
declare v_report public.transfer_reports%rowtype;v_account public.credit_accounts%rowtype;v_remaining numeric;v_installment public.credit_installments%rowtype;v_has_overdue boolean;
begin
 select * into v_report from public.transfer_reports where id=p_report_id and organization_id=private.current_organization_id()for update;if not found or not private.has_permission('payments.validate')then raise exception 'No autorizado' using errcode='42501';end if;if v_report.status not in('reported','under_review')then raise exception 'El reporte ya fue procesado';end if;
 if not p_approve then update public.transfer_reports set status='rejected'where id=v_report.id;insert into public.transfer_validation_events(organization_id,transfer_report_id,from_status,to_status,actor_id,notes)values(v_report.organization_id,v_report.id,v_report.status,'rejected',auth.uid(),coalesce(p_notes,'Rechazado'));return;end if;
 select * into v_account from public.credit_accounts where application_id=v_report.credit_application_id for update;if not found then raise exception 'No existe cuenta de crédito activa';end if;insert into public.payment_applications(organization_id,transfer_report_id,account_id,amount,applied_by)values(v_report.organization_id,v_report.id,v_account.id,v_report.amount,auth.uid());v_remaining=v_report.amount;
 for v_installment in select * from public.credit_installments where account_id=v_account.id and status in('pending','partial','overdue')order by installment_number for update loop exit when v_remaining<=0;update public.credit_installments set paid_amount=least(amount,paid_amount+v_remaining),status=case when paid_amount+v_remaining>=amount then 'paid'when due_date<current_date then 'overdue'else 'partial'end where id=v_installment.id;v_remaining=greatest(0,v_remaining-(v_installment.amount-v_installment.paid_amount));end loop;
 select exists(select 1 from public.credit_installments where account_id=v_account.id and due_date<current_date and status<>'paid')into v_has_overdue;
 update public.credit_accounts set outstanding_balance=greatest(0,outstanding_balance-v_report.amount),status=case when outstanding_balance-v_report.amount<=0 then 'paid'when v_has_overdue then 'delinquent'else 'active'end where id=v_account.id;update public.transfer_reports set status='applied'where id=v_report.id;insert into public.transfer_validation_events(organization_id,transfer_report_id,from_status,to_status,actor_id,notes)values(v_report.organization_id,v_report.id,v_report.status,'applied',auth.uid(),coalesce(p_notes,'Pago validado y aplicado'));
end $$;

-- Recalcula la mora de cuentas existentes tras pagos parciales.
update public.credit_installments set status='overdue'where due_date<current_date and paid_amount<amount;
update public.credit_accounts ca set status='delinquent'where status<>'paid'and exists(select 1 from public.credit_installments i where i.account_id=ca.id and i.status='overdue');
