create extension if not exists pgcrypto;
create type public.entity_status as enum ('active','inactive');
create type public.inventory_status as enum ('available','reserved','transfer_pending','in_transit','sold_cash','financed_active','delinquent','restricted','warranty','repair','recovered','released','lost');
create type public.transfer_status as enum ('requested','approved','preparing','dispatched','in_transit','received','received_with_discrepancy','rejected','cancelled','lost');
create type public.credit_application_status as enum ('draft','documents_pending','submitted','under_review','additional_information_required','preapproved','approved','rejected','contract_pending','signed','device_setup_pending','ready_for_delivery','activated','cancelled');
create type public.transfer_report_status as enum ('reported','under_review','confirmed','rejected','duplicate_suspected','applied','reversed');

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,commercial_name text not null,status entity_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.business_units(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,name text generated always as (commercial_name) stored,legal_name text not null,commercial_name text not null,owner_name text not null,rtn text,status entity_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,rtn));
create table public.branches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,business_unit_id uuid not null references business_units,name text not null,code text not null,branch_type text not null check(branch_type in ('store','warehouse','office')),address text not null,phone text,status entity_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table public.profiles(id uuid primary key references auth.users on delete cascade,organization_id uuid not null references organizations,full_name text not null,status entity_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.roles(id uuid primary key default gen_random_uuid(),organization_id uuid references organizations,name text not null,description text not null default '',is_system boolean not null default false,unique(organization_id,name));
create table public.permissions(id uuid primary key default gen_random_uuid(),code text not null unique,description text not null);
create table public.role_permissions(role_id uuid not null references roles on delete cascade,permission_id uuid not null references permissions on delete cascade,primary key(role_id,permission_id));
create table public.profile_roles(profile_id uuid not null references profiles on delete cascade,role_id uuid not null references roles on delete cascade,primary key(profile_id,role_id));
create table public.user_branch_access(profile_id uuid not null references profiles on delete cascade,branch_id uuid not null references branches on delete cascade,can_manage boolean not null default false,primary key(profile_id,branch_id));

create table public.configuration_definitions(id uuid primary key default gen_random_uuid(),key text not null unique,description text not null,value_type text not null check(value_type in ('string','number','boolean','json')),allowed_scope_types text[] not null,created_at timestamptz not null default now());
create table public.configuration_versions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,version integer not null,status text not null check(status in ('draft','active','retired')),published_by uuid references profiles,published_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,version));
create table public.configuration_scopes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,scope_type text not null check(scope_type in ('organization','business_unit','branch','customer_type','category','brand','model','price_range','credit_product','campaign')),scope_id uuid not null,attributes jsonb not null default '{}',unique(organization_id,scope_type,scope_id));
create table public.configuration_values(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,definition_id uuid not null references configuration_definitions,scope_id uuid not null references configuration_scopes,version_id uuid not null references configuration_versions,value jsonb not null,priority integer not null default 0,effective_from timestamptz not null,effective_until timestamptz,status text not null check(status in ('draft','active','retired')),check(effective_until is null or effective_until>effective_from));
create table public.configuration_audit_logs(id bigint generated always as identity primary key,organization_id uuid not null references organizations,configuration_value_id uuid references configuration_values,actor_id uuid references profiles,action text not null,before_value jsonb,after_value jsonb,created_at timestamptz not null default now());

create table public.rule_sets(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,name text not null,version integer not null,status text not null check(status in ('draft','active','retired')),created_at timestamptz not null default now());
create table public.business_rules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,rule_set_id uuid not null references rule_sets,code text not null,name text not null,priority integer not null,enabled boolean not null default true,unique(rule_set_id,code));
create table public.rule_conditions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,rule_id uuid not null references business_rules on delete cascade,field text not null,operator text not null check(operator in ('equals','not_equals','greater_than','greater_than_or_equal','less_than','less_than_or_equal','in','not_in','between')),operand jsonb not null,position integer not null,unique(rule_id,position));
create table public.rule_actions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,rule_id uuid not null references business_rules on delete cascade,action_type text not null check(action_type in ('set_minimum_down_payment','set_maximum_term','set_interest_rate','require_document','require_supervisor_approval','reject_application','add_warning')),value jsonb not null,position integer not null,unique(rule_id,position));
create table public.rule_execution_logs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,rule_set_id uuid not null references rule_sets,subject_type text not null,subject_id uuid,inputs jsonb not null,evaluations jsonb not null,result jsonb not null,executed_by uuid references profiles,created_at timestamptz not null default now());

create table public.customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,normalized_dni text not null,first_name text not null,last_name text not null,phone text not null,email text,customer_type text not null default 'new',created_by uuid references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,normalized_dni));
create table public.customer_addresses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,address_type text not null,address text not null,proof_type text check(proof_type in ('energy','water','internet','cable','phone','rent','other')),proof_holder_name text,holder_relationship text,created_at timestamptz not null default now());
create table public.customer_employment(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,employer_name text not null,position text,monthly_income numeric(14,2),started_on date,created_at timestamptz not null default now());
create table public.customer_references(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,name text not null,relationship text not null,phone text not null,created_at timestamptz not null default now());
create table public.customer_documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,document_type text not null check(document_type in ('dni_front','dni_back','selfie','address_proof','other')),storage_path text not null unique,metadata jsonb not null default '{}',created_at timestamptz not null default now(),check(storage_path ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}/[0-9a-f-]{36}/'));
create table public.customer_consents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,consent_type text not null,version text not null,granted boolean not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.customer_timeline_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers on delete cascade,event_type text not null,description text not null,metadata jsonb not null default '{}',actor_id uuid references profiles,created_at timestamptz not null default now());

create table public.product_brands(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,name text not null,status entity_status not null default 'active',unique(organization_id,name));
create table public.product_models(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,brand_id uuid not null references product_brands,name text not null,category text not null default 'phone',status entity_status not null default 'active',unique(organization_id,brand_id,name));
create table public.inventory_units(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,owner_business_unit_id uuid not null references business_units,current_branch_id uuid not null references branches,brand_id uuid not null references product_brands,model_id uuid not null references product_models,imei_1 text not null,imei_2 text,serial_number text,color text,storage_capacity text,ram_capacity text,cost numeric(14,2) not null check(cost>=0),cash_price numeric(14,2) not null check(cash_price>=0),condition text not null,mdm_compatible boolean not null default false,status inventory_status not null default 'available',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,imei_1),unique(organization_id,imei_2),unique(organization_id,serial_number));
create table public.inventory_unit_movements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,inventory_unit_id uuid not null references inventory_units,from_branch_id uuid references branches,to_branch_id uuid references branches,from_owner_business_unit_id uuid references business_units,to_owner_business_unit_id uuid references business_units,movement_type text not null,reference_type text,reference_id uuid,actor_id uuid references profiles,created_at timestamptz not null default now());
create table public.inventory_transfers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,origin_branch_id uuid not null references branches,destination_branch_id uuid not null references branches,transfer_ownership boolean not null default false,destination_owner_business_unit_id uuid references business_units,status transfer_status not null default 'requested',requested_by uuid not null references profiles,approved_by uuid references profiles,dispatched_by uuid references profiles,received_by uuid references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(origin_branch_id<>destination_branch_id));
create table public.inventory_transfer_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,transfer_id uuid not null references inventory_transfers on delete cascade,inventory_unit_id uuid not null references inventory_units,origin_scanned_at timestamptz,destination_scanned_at timestamptz,unique(transfer_id,inventory_unit_id));
create table public.inventory_transfer_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,transfer_id uuid not null references inventory_transfers,event_type text not null,actor_id uuid not null references profiles,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.inventory_transfer_discrepancies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,transfer_id uuid not null references inventory_transfers,expected_inventory_unit_id uuid references inventory_units,scanned_imei text,description text not null,resolved_at timestamptz,created_at timestamptz not null default now());

create table public.credit_applications(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,branch_id uuid not null references branches,business_unit_id uuid not null references business_units,customer_id uuid not null references customers,assigned_analyst_id uuid references profiles,inventory_unit_id uuid references inventory_units,requested_price numeric(14,2) not null,proposed_down_payment numeric(14,2) not null,proposed_term integer not null,status credit_application_status not null default 'draft',configuration_version_id uuid references configuration_versions,created_by uuid not null references profiles,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.credit_application_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications on delete cascade,inventory_unit_id uuid references inventory_units,description text not null,price numeric(14,2) not null);
create table public.credit_application_status_history(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications,status credit_application_status not null,actor_id uuid not null references profiles,reason text,created_at timestamptz not null default now());
create table public.credit_application_notes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications,note text not null,visibility text not null default 'internal',author_id uuid not null references profiles,created_at timestamptz not null default now());
create table public.credit_application_assignments(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications,analyst_id uuid not null references profiles,assigned_by uuid not null references profiles,assigned_at timestamptz not null default now(),ended_at timestamptz);
create table public.credit_decisions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications,decision text not null check(decision in ('preapproved','approved','rejected','additional_information_required')),reason text not null,conditions jsonb not null default '[]',decided_by uuid not null references profiles,created_at timestamptz not null default now());

create table public.bank_accounts(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,business_unit_id uuid not null references business_units,bank_name text not null,account_name text not null,masked_account_number text not null,status entity_status not null default 'active');
create table public.transfer_reports(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,customer_id uuid not null references customers,credit_application_id uuid references credit_applications,bank_account_id uuid not null references bank_accounts,origin_bank text not null,amount numeric(14,2) not null check(amount>0),transferred_on date not null,approximate_time time,reference_number text not null,sender_account_holder text not null,status transfer_report_status not null default 'reported',created_at timestamptz not null default now());
create unique index transfer_reports_potential_duplicate on transfer_reports(organization_id,lower(reference_number),amount,transferred_on) where status not in ('rejected','reversed');
create table public.transfer_report_files(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,transfer_report_id uuid not null references transfer_reports,storage_path text not null unique,created_at timestamptz not null default now());
create table public.transfer_validation_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,transfer_report_id uuid not null references transfer_reports,from_status transfer_report_status,to_status transfer_report_status not null,actor_id uuid references profiles,notes text not null,created_at timestamptz not null default now());
create table public.audit_logs(id bigint generated always as identity primary key,organization_id uuid not null references organizations,branch_id uuid references branches,user_id uuid references profiles,entity_type text not null,entity_id uuid,action text not null,before_values jsonb,after_values jsonb,metadata jsonb not null default '{}',created_at timestamptz not null default now());
