create table public.credit_risk_assessments(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,application_id uuid not null references credit_applications on delete cascade,
 score integer not null check(score between 0 and 100),recommendation text not null check(recommendation in('approve','manual_review','condition','reject')),
 disposable_income numeric(14,2)not null,payment_to_income_ratio numeric(8,4)not null,factors jsonb not null default'[]',calculated_by uuid references profiles,created_at timestamptz not null default now()
);
alter table public.credit_risk_assessments enable row level security;alter table public.credit_risk_assessments force row level security;
create policy assessment_scoped_read on public.credit_risk_assessments for select to authenticated using(organization_id=private.current_organization_id()and exists(select 1 from public.credit_applications a where a.id=application_id and(private.has_role('organization_owner')or private.has_role('organization_admin')or private.has_role('credit_manager')or private.has_branch_access(a.branch_id))));
grant select on public.credit_risk_assessments to authenticated;

create or replace function public.refresh_credit_assessment(p_application_id uuid)returns jsonb language plpgsql security definer set search_path='' as $$
declare v_app public.credit_applications%rowtype;v_profile public.credit_application_profiles%rowtype;v_score integer:=50;v_disposable numeric;v_installment numeric;v_ratio numeric;v_down_ratio numeric;v_docs integer;v_rec text;v_factors jsonb:='[]'::jsonb;begin select * into v_app from public.credit_applications where id=p_application_id and organization_id=private.current_organization_id();select * into v_profile from public.credit_application_profiles where application_id=p_application_id;if not found or not(private.has_permission('applications.create')or private.has_permission('applications.review')or private.has_role('organization_owner')or private.has_role('organization_admin'))then raise exception'No autorizado';end if;v_disposable=v_profile.monthly_income-v_profile.monthly_expenses;v_installment=round((v_app.requested_price-v_app.proposed_down_payment)/v_app.proposed_term,2);v_ratio=case when v_profile.monthly_income>0 then v_installment/v_profile.monthly_income else 1 end;v_down_ratio=v_app.proposed_down_payment/v_app.requested_price;select count(distinct document_type)into v_docs from public.customer_documents where customer_id=v_app.customer_id and document_type in('dni_front','dni_back','selfie','address_proof');
 if v_ratio<=.15 then v_score=v_score+20;v_factors=v_factors||jsonb_build_array('Cuota menor o igual al 15% del ingreso');elsif v_ratio<=.30 then v_score=v_score+10;v_factors=v_factors||jsonb_build_array('Cuota entre 15% y 30% del ingreso');else v_score=v_score-20;v_factors=v_factors||jsonb_build_array('Cuota superior al 30% del ingreso');end if;
 if v_profile.employment_months>=24 then v_score=v_score+10;v_factors=v_factors||jsonb_build_array('Estabilidad laboral mayor a 24 meses');elsif v_profile.employment_months<6 then v_score=v_score-10;v_factors=v_factors||jsonb_build_array('Antigüedad laboral menor a 6 meses');end if;
 if v_down_ratio>=.30 then v_score=v_score+10;v_factors=v_factors||jsonb_build_array('Prima igual o superior al 30%');elsif v_down_ratio<.10 then v_score=v_score-10;v_factors=v_factors||jsonb_build_array('Prima inferior al 10%');end if;
 if v_docs=4 then v_score=v_score+10;v_factors=v_factors||jsonb_build_array('Expediente documental completo');else v_score=v_score-10;v_factors=v_factors||jsonb_build_array('Faltan documentos obligatorios');end if;v_score=greatest(0,least(100,v_score));v_rec=case when v_score>=75 then'approve'when v_score>=60 then'manual_review'when v_score>=45 then'condition'else'reject'end;
 insert into public.credit_risk_assessments(organization_id,application_id,score,recommendation,disposable_income,payment_to_income_ratio,factors,calculated_by)values(v_app.organization_id,v_app.id,v_score,v_rec,v_disposable,v_ratio,v_factors,auth.uid());return jsonb_build_object('score',v_score,'recommendation',v_rec,'disposable_income',v_disposable,'payment_to_income_ratio',v_ratio,'factors',v_factors);end$$;
revoke all on function public.refresh_credit_assessment(uuid)from public,anon;grant execute on function public.refresh_credit_assessment(uuid)to authenticated;
