create table public.team_invitations(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations,email text not null,full_name text not null,
 role_name text not null,branch_id uuid references branches,token uuid not null default gen_random_uuid()unique,invited_by uuid not null references profiles,
 expires_at timestamptz not null default(now()+interval'7 days'),accepted_at timestamptz,created_at timestamptz not null default now()
);
alter table public.team_invitations enable row level security;alter table public.team_invitations force row level security;
create policy invitations_admin_read on public.team_invitations for select to authenticated using(organization_id=private.current_organization_id()and(private.has_role('organization_owner')or private.has_role('organization_admin')));
grant select on public.team_invitations to authenticated;

create or replace function public.create_branch(p_name text,p_code text,p_address text,p_phone text default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_org uuid;v_unit uuid;v_id uuid;begin v_org=private.current_organization_id();if v_org is null or not(private.has_role('organization_owner')or private.has_role('organization_admin'))then raise exception'No autorizado'using errcode='42501';end if;if nullif(trim(p_name),'')is null or nullif(trim(p_code),'')is null or nullif(trim(p_address),'')is null then raise exception'Complete los datos de la tienda';end if;select id into v_unit from public.business_units where organization_id=v_org and status='active'order by created_at limit 1;insert into public.branches(organization_id,business_unit_id,name,code,branch_type,address,phone)values(v_org,v_unit,trim(p_name),upper(trim(p_code)),'store',trim(p_address),nullif(trim(p_phone),''))returning id into v_id;return v_id;end$$;
revoke all on function public.create_branch(text,text,text,text)from public,anon;grant execute on function public.create_branch(text,text,text,text)to authenticated;

create or replace function public.create_team_invitation(p_email text,p_full_name text,p_role_name text,p_branch_id uuid default null)
returns uuid language plpgsql security definer set search_path='' as $$
declare v_org uuid;v_token uuid;begin v_org=private.current_organization_id();if v_org is null or not(private.has_role('organization_owner')or private.has_role('organization_admin'))then raise exception'No autorizado'using errcode='42501';end if;if p_role_name not in('organization_admin','branch_manager','credit_analyst','credit_manager','salesperson','cashier','inventory_manager','collections_agent','auditor')then raise exception'Rol inválido';end if;if p_role_name not in('organization_admin','credit_manager','auditor')and(p_branch_id is null or not exists(select 1 from public.branches where id=p_branch_id and organization_id=v_org))then raise exception'Seleccione una tienda válida';end if;update public.team_invitations set expires_at=now()where organization_id=v_org and lower(email)=lower(trim(p_email))and accepted_at is null and expires_at>now();insert into public.team_invitations(organization_id,email,full_name,role_name,branch_id,invited_by)values(v_org,lower(trim(p_email)),trim(p_full_name),p_role_name,p_branch_id,auth.uid())returning token into v_token;return v_token;end$$;
revoke all on function public.create_team_invitation(text,text,text,uuid)from public,anon;grant execute on function public.create_team_invitation(text,text,text,uuid)to authenticated;

create or replace function public.accept_team_invitation(p_token uuid)
returns void language plpgsql security definer set search_path='' as $$
declare v_inv public.team_invitations%rowtype;v_role uuid;v_email text;begin select * into v_inv from public.team_invitations where token=p_token and accepted_at is null and expires_at>now()for update;if not found then raise exception'Invitación inválida o vencida';end if;v_email=lower(coalesce(auth.jwt()->>'email',''));if auth.uid()is null or v_email<>lower(v_inv.email)then raise exception'La invitación pertenece a otro correo';end if;if exists(select 1 from public.profiles where id=auth.uid())then raise exception'Este usuario ya pertenece a una organización';end if;insert into public.profiles(id,organization_id,full_name)values(auth.uid(),v_inv.organization_id,v_inv.full_name);select id into v_role from public.roles where organization_id=v_inv.organization_id and name=v_inv.role_name;insert into public.profile_roles(profile_id,role_id)values(auth.uid(),v_role);if v_inv.branch_id is not null then insert into public.user_branch_access(profile_id,branch_id,can_manage)values(auth.uid(),v_inv.branch_id,v_inv.role_name='branch_manager');end if;update public.team_invitations set accepted_at=now()where id=v_inv.id;end$$;
revoke all on function public.accept_team_invitation(uuid)from public,anon;grant execute on function public.accept_team_invitation(uuid)to authenticated;
